import Foundation
import Testing

@testable import EnviousWisprPostProcessing

/// Behavioral-parity gate for the Swift ITN port (#145).
///
/// The validated Python normalizer (`EnviousWispr-artifacts/.../candidates/hand_rolled.py`)
/// is the ORACLE. `parity.jsonl` bakes its output for every curated benchmark input
/// (input → `normalize_python(input)`), generated by `gen_parity_fixture.py`. These tests
/// assert the Swift engine reproduces the oracle byte-for-byte, plus the load-bearing
/// safety properties (no-corruption, idempotence) and the specific fixes the fresh-data
/// validation surfaced (o→0 phones, year-pairs, keep-magnitude house style).
///
/// Fixture is loaded from disk via `#filePath` → repo root (the OutputClassifier parity
/// precedent), so the test is hermetic and CI-safe with no `resources:` glob.
struct InverseTextNormalizerParityTests {

  struct Row: Decodable {
    let input: String
    let expected: String
    let category: String
    let slice: String
  }

  /// `<repo>/Tests/EnviousWisprTests/Resources/InverseTextNormalizer/`.
  static let resourceDir: URL = URL(filePath: #filePath)
    .deletingLastPathComponent()  // PostProcessing
    .deletingLastPathComponent()  // EnviousWisprTests
    .deletingLastPathComponent()  // Tests
    .deletingLastPathComponent()  // repo root
    .appending(path: "Tests/EnviousWisprTests/Resources/InverseTextNormalizer")

  static func loadRows(_ file: String = "parity.jsonl") throws -> [Row] {
    let text = try String(contentsOf: resourceDir.appending(path: file), encoding: .utf8)
    let decoder = JSONDecoder()
    return try text.split(separator: "\n").compactMap { line in
      let trimmed = line.trimmingCharacters(in: .whitespaces)
      guard trimmed.isEmpty == false else { return nil }
      return try decoder.decode(Row.self, from: Data(trimmed.utf8))
    }
  }

  /// Byte-for-byte compare the Swift engine against the oracle outputs in `rows`.
  /// Records a per-category breakdown + sample on failure; returns the mismatch count.
  static func checkParity(_ rows: [Row], label: String) -> Int {
    let itn = InverseTextNormalizer()
    var mismatches: [(Row, String)] = []
    var perCategoryTotal: [String: Int] = [:]
    var perCategoryFail: [String: Int] = [:]
    for row in rows {
      perCategoryTotal[row.category, default: 0] += 1
      let got = itn.normalize(row.input, spokenPunctuation: true)
      if got != row.expected {
        perCategoryFail[row.category, default: 0] += 1
        if mismatches.count < 40 { mismatches.append((row, got)) }
      }
    }
    let failCount = perCategoryFail.values.reduce(0, +)
    if failCount > 0 {
      let sample = mismatches.map { item -> String in
        let (r, got) = item
        return "  [\(r.category)/\(r.slice)] in=\(r.input.debugDescription) "
          + "want=\(r.expected.debugDescription) got=\(got.debugDescription)"
      }.joined(separator: "\n")
      let byCat = perCategoryFail.sorted { $0.key < $1.key }
        .map { "\($0.key): \($0.value)/\(perCategoryTotal[$0.key] ?? 0)" }
        .joined(separator: ", ")
      let msg =
        "ITN parity [\(label)]: \(failCount)/\(rows.count) mismatches vs Python oracle.\n"
        + "By category (fail/total): \(byCat)\nFirst \(mismatches.count):\n\(sample)"
      Issue.record("\(msg)")
    }
    return failCount
  }

  /// Two degenerate oracle inputs are non-idempotent in the Python reference too (a 17-word
  /// "quadrillion" mega-number and a malformed "point five o six dollars" with no leading
  /// whole). Excluded from the idempotence property, NOT from parity — Swift still matches
  /// the oracle's first-pass output for both.
  static let knownNonIdempotentInputs: Set<String> = [
    "ninety seven quadrillion eight hundred eight trillion two hundred sixty four billion "
      + "seven hundred seventy two million seven hundred ninety two thousand five",
    "point five o six dollars",
    // #2257: urls(_:)'s trailing-continuation guard matches the spoken word "question
    // mark"; once spokenPunctuation converts it to a literal "?" on the first pass, the
    // guard's own signal is gone (round 16 deliberately dropped the tight-symbol form
    // of this guard — see followedByUnsupportedContinuation's own comment for why) and
    // the second pass converts the path it had deliberately left alone. Not a
    // corruption either pass — the second-pass output is strictly MORE normalized, not
    // wrong — but not a fixed point. The protocol-prefix guard's sibling case (a
    // "colon" materializing the same way) is genuinely idempotent as of round 14: that
    // guard DOES recognize the materialized ":" on the second pass too, so it stays
    // OUT of this list on purpose (round 16 P3) rather than hiding its own coverage.
    "example.com slash search question mark q equals test",
  ]

  // MARK: - Primary: byte-for-byte parity with the Python oracle

  @Test("Swift ITN matches the Python oracle byte-for-byte across the curated corpus")
  func byteForByteParity() throws {
    let rows = try Self.loadRows()
    #expect(rows.count > 1500, "parity fixture looks truncated: \(rows.count) rows")
    #expect(Self.checkParity(rows, label: "curated") == 0)
  }

  /// Independent-data faithfulness: rows NOT baked into the curated fixture (the synthetic
  /// holdout + the public Google-TN set + real dictations, deduped against `parity.jsonl`).
  /// Passing here means the port is faithful to the oracle on UNSEEN inputs, not just the
  /// cases captured at build time.
  @Test("Swift ITN matches the oracle on the independent holdout (unseen inputs)")
  func holdoutParity() throws {
    let rows = try Self.loadRows("parity_holdout.jsonl")
    #expect(rows.count > 3000, "holdout fixture looks truncated: \(rows.count) rows")
    #expect(Self.checkParity(rows, label: "holdout") == 0)
  }

  // MARK: - Safety property: no corruption of natural prose (heaviest-weighted rubric)

  @Test("Natural-speech negatives pass through unchanged (no-corruption floor)")
  func negativesArePreserved() throws {
    let rows = try Self.loadRows().filter { $0.slice == "negative" }
    #expect(rows.isEmpty == false)
    let itn = InverseTextNormalizer()
    var corrupted: [(String, String)] = []
    for row in rows where itn.normalize(row.input, spokenPunctuation: true) != row.expected {
      corrupted.append((row.input, itn.normalize(row.input, spokenPunctuation: true)))
    }
    // Parity already pins these to the oracle; this is a focused readout of the safety floor.
    #expect(corrupted.isEmpty, "negatives diverged from oracle: \(corrupted.prefix(10))")
  }

  // MARK: - Safety property: idempotence (normalize is a fixed point of itself)

  @Test("Idempotence: normalizing an already-normalized output is a no-op")
  func idempotence() throws {
    let rows = try Self.loadRows()
    let itn = InverseTextNormalizer()
    var unstable: [(String, String, String)] = []
    for row in rows where Self.knownNonIdempotentInputs.contains(row.input) == false {
      let once = itn.normalize(row.input, spokenPunctuation: true)
      let twice = itn.normalize(once, spokenPunctuation: true)
      if twice != once {
        unstable.append((row.input, once, twice))
      }
    }
    #expect(
      unstable.isEmpty,
      "non-idempotent (beyond the 2 known degenerate inputs): \(unstable.prefix(10))")
  }

  // MARK: - Targeted: the specific fixes fresh-data validation surfaced

  // Expected values below are the verbatim Python-oracle outputs (verified at port time),
  // NOT hand-guessed — each demonstrates one fix the fresh-data validation surfaced.
  @Test(
    "Category fixes hold (oracle-verified)",
    arguments: [
      // o→0 in spoken digit reads, 10-digit phone — fix #5
      ("my number is o five five five one two three four five six", "my number is 055-512-3456"),
      // year-pair standalone — fix #6 / founder option 1
      ("i was born in nineteen eighty seven", "i was born in 1987"),
      // keep-magnitude house style — fix #7
      ("we raised eighty million dollars last year", "we raised $80 million last year"),
      // word-driven digit read with a zero-word, length ≤ 6
      ("the code is two zero three", "the code is 203"),
      // mixed-state phone (already-digit group + digit-words) — fix #4
      ("call me at 203 nine five four eight eight seven nine", "call me at 203-954-8879"),
      // strict-cardinal corruption guard: a non-cardinal run is left untouched (context for
      // "one twenty" belongs to the AI-polish layer, not the deterministic floor)
      ("there were one twenty people there", "there were one twenty people there"),
      // #145 follow-up: capitalized number words in an UNIT-ANCHORED numeric context
      // (currency / percent / decimal point) now format — they did not before because the
      // lexicon lookups were case-sensitive.
      ("Twenty dollars please", "$20 please"),
      ("Twenty percent off", "20% off"),
      // crash guard: a title-cased decimal must format, not trap on the force-unwrapped fraction
      // word ('Five'); the case-insensitive regex captures it, so the digit map must lowercase.
      ("Three Point Five", "3.5"),
      // adversarial negatives: a capitalized number word with NO unit anchor must stay a word,
      // never corrupt into a digit — covers prose ("One thing", "Two of us") AND proper nouns
      // that contain a scale word ("Hundred Acre Wood", "One Million Moms"). A bare/scale-only
      // capital is ambiguous between count and name, so the deterministic floor leaves it.
      ("One thing that I want to figure out", "One thing that I want to figure out"),
      ("Two of us went to the store", "Two of us went to the store"),
      ("Hundred Acre Wood", "Hundred Acre Wood"),
      ("One Million Moms", "One Million Moms"),
    ])
  func categoryFixes(input: String, expected: String) {
    #expect(InverseTextNormalizer().normalize(input, spokenPunctuation: true) == expected)
  }

  // AP-style number formatting (#1187). Spell one-nine; digits for 10+; always-digit exceptions
  // for money/percent/age/units/decimals/ranges/ordinals-10th+. Each line is the verbatim Python
  // oracle output (the byte-parity fixtures lock the full set; these document the policy in-place).
  @Test(
    "AP number policy holds (oracle-verified)",
    arguments: [
      // the #1187 report: a sentence-initial spelled-out large number was passing through untouched
      ("Nine hundred forty five.", "945."),
      // spell out one-nine in prose (the founder feedback: "they said 1, it wrote 1")
      ("I have two cats.", "I have two cats."),
      ("twenty three people came", "23 people came"),
      // exceptions still digitize sub-ten values
      ("she is five years old", "she is 5 years old"),
      ("walk five miles", "walk 5 miles"),
      // per-token in a mixed sentence (one stays spelled, one converts)
      ("nine out of ten dentists", "nine out of 10 dentists"),
      // ranges -> hyphenated digits; small ordinals stay spelled, 10th+ convert
      ("between three and seven", "between 3-7"),
      ("the third option is best", "the third option is best"),
      ("the twentieth century", "the 20th century"),
      ("the hundred and first complaint", "the 101st complaint"),
      // spoken decimals; money at sentence end keeps the dollar sign
      ("negative point five", "negative 0.5"),
      ("He paid fifteen hundred dollars.", "He paid $1,500."),
      // brands/titles with a number word stay spelled
      ("we ate at Five Guys", "we ate at Five Guys"),
    ])
  func apNumberPolicy(input: String, expected: String) {
    #expect(InverseTextNormalizer().normalize(input, spokenPunctuation: true) == expected)
  }

  // Codex-finding regressions from PR #1191's review. Fix 1: keep-magnitude must never rewrite
  // a PARTIAL comma group (a complete comma-grouped number is never followed by ",digit", so the
  // (?!,\d) guard only blocks backtracked prefixes). Fix 2: the pad-space rejoin must accept our
  // own ordinal-suffix emissions ("23rd"), not only bare digits ("20").
  @Test(
    "Codex-finding regressions hold (#1201/#1202)",
    .bug("https://github.com/saurabhav88/EnviousWispr/issues/1201", "scale ordinals >= billion"),
    .bug("https://github.com/saurabhav88/EnviousWispr/issues/1202", "hyphenated ordinal rejoin"),
    arguments: [
      // #1201: billion-scale ordinal survives keep-magnitude intact (was "1 million,000th")
      ("one billionth", "1,000,000,000th"),
      // leading coefficient on a billion-scale ordinal (was "2 million,000th")
      ("two billionth", "2,000,000,000th"),
      // same defect class through the currency-decimal guard: the (?!\.\d) block on the full
      // match let keep-magnitude backtrack onto the "5,000,000" prefix (was "$5 million,000.00")
      ("$5,000,000,000.00", "$5,000,000,000.00"),
      // keep-magnitude positives must keep converting (guard is partial-groups only)
      ("we raised eighty million dollars", "we raised $80 million"),
      ("the deal was worth three billion dollars", "the deal was worth $3 billion"),
      // millionth was accidentally safe before the fix and must stay safe after it
      ("one millionth", "1,000,000th"),
      // fraction guard unaffected: "of" keeps the spelled form
      ("a billionth of a second", "a billionth of a second"),
      // plural / multiplier suffixes ride the same partial-group class: preserve unchanged
      // (old code corrupted both to "1 million,000s" / "1 million,000x")
      ("the count is in the 1,000,000,000s now", "the count is in the 1,000,000,000s now"),
      ("roughly 1,000,000,000x faster", "roughly 1,000,000,000x faster"),
      // #1202: hyphenated compound-ordinal modifier rejoins (was "23rd -century art")
      ("twenty-third-century art", "23rd-century art"),
      ("her twenty-first-birthday party", "her 21st-birthday party"),
      // digit-cardinal rejoin (pre-existing behavior) must keep working
      ("a twenty-step process", "a 20-step process"),
      // hyphen followed by a space is prose punctuation, never rejoined
      ("she came 3rd - not bad", "she came 3rd - not bad"),
    ])
  func codexFindingRegressions(input: String, expected: String) {
    #expect(InverseTextNormalizer().normalize(input, spokenPunctuation: true) == expected)
  }

  // #2315: spoken web addresses come out broken — trailing periods, a stray trailing "dot"
  // word, and a garbled "https" prefix. Each row demonstrates one fix; the regression-guard
  // row confirms the fix does not reopen the #2257-era "dot s m" bug the file's own comment
  // on `spokenPat` warns about.
  //
  // Expected values are ITN-ONLY output (this test calls `normalize(_:)` directly, not the
  // full pipeline): ITN converts spoken dot/slash into real punctuation and strips the
  // recognizer's own trailing-period/stray-dot artifacts, but it does not materialize a
  // spoken "slash slash" protocol connector into "://" — that reconstruction is LLM polish's
  // job downstream, unchanged by this fix.
  //
  // KNOWN, PRE-EXISTING, OUT-OF-SCOPE BOUNDARY: a domain immediately preceded by "slash" —
  // as in a spoken "https slash slash" protocol prefix — never reaches spokenPat/joinedPat's
  // conversion at all. `precededByUnresolvedConnector` (this file, unrelated to and unchanged
  // by this fix) already treats "slash" as one of its dangling-connector-word signals and
  // refuses the WHOLE match, so the host/tld dot-conversion this PR adds trailer handling to
  // never fires there either — the last two rows below document this AS-IS rather than
  // asserting the aspirational fully-cleaned form. Changing that guard's established
  // "slash" membership is a separate, larger decision (it exists to avoid a worse dangling
  // partial conversion) and is out of scope here.
  @Test(
    "#2315 spoken web addresses: trailing period, stray dot, garbled https prefix",
    .bug("https://github.com/saurabhav88/EnviousWispr/issues/2315", "spoken web address cleanup"),
    arguments: [
      // Fix 1: a bare URL-only utterance's recognizer-added period is dropped.
      ("facebook dot com.", "facebook.com"),
      // Fix 1 (negative): the identical trailing period on a real sentence is kept.
      ("I visited facebook dot com.", "I visited facebook.com."),
      // Fix 2: a stray trailing "dot"/"dot." word survives a spoken-shape conversion.
      ("facebook dot com dot.", "facebook.com."),
      ("facebook dot com dot", "facebook.com."),
      // Fix 2, ASR-pre-joined bare-domain shape (no path — outside joinedPat's own scope,
      // handled by the dedicated bare-trailer pass).
      ("www.facebook.com dot.", "www.facebook.com."),
      // Fix 2 (negative): a real mid-utterance continuation after the domain must not be
      // swallowed into the address (the "5%" is separate, pre-existing percent conversion,
      // unrelated to and unaffected by this fix).
      ("facebook.com dot five percent off", "facebook.com dot 5% off"),
      // Fix 3: a garbled "H slash slash" (truncated "https") is normalized to the full word,
      // reaching polish as unambiguous text instead of a dangling "H" — see the boundary
      // note above for why the domain itself stays dot-unconverted here.
      ("H slash slash facebook dot com", "https slash slash facebook dot com"),
      // Fix 3 (negative, cloud review PR #2463): "H slash slash" with no URL-shaped
      // continuation is ordinary technical dictation, not a truncated https, and must be
      // left untouched.
      (
        "the variable H slash slash is malformed", "the variable H slash slash is malformed"
      ),
      // Boundary (see note above): a cleanly-heard "https slash slash" prefix already blocks
      // dot-conversion today, independent of this fix — documented, not asserted as fixed.
      ("https slash slash facebook dot com.", "https slash slash facebook dot com."),
      // Regression guard (#2257-era): the letter-spelled "h t t p" shape must still leave an
      // unrelated trailing "dot s m" continuation untouched — this fix must not reopen it.
      (
        "h t t p colon slash slash w w w dot o u r d a i l y n e w s dot com dot s m",
        "h t t p: slash slash w w w dot o u r d a i l y n e w s.com dot s m"
      ),
    ])
  func issue2315SpokenURLCleanup(input: String, expected: String) {
    #expect(InverseTextNormalizer().normalize(input, spokenPunctuation: true) == expected)
  }
}
