import Foundation
import Testing

@testable import EnviousWisprPostProcessing

/// Behavioral-parity gate for the Swift ITN port (#145).
///
/// The validated Python normalizer (`EnviousWispr-artifacts/.../candidates/hand_rolled.py`)
/// is the ORACLE. `parity.jsonl` bakes its output for every curated benchmark input
/// (input → `normalize_python(input)`), generated by `gen_parity_fixture.py`. These tests
/// assert the Swift engine reproduces the oracle byte-for-byte, plus the load-bearing
/// safety properties (no-corruption, idempotence) and the specific fixes the fresh-data
/// validation surfaced (o→0 phones, year-pairs, keep-magnitude house style).
///
/// Fixture is loaded from disk via `#filePath` → repo root (the OutputClassifier parity
/// precedent), so the test is hermetic and CI-safe with no `resources:` glob.
struct InverseTextNormalizerParityTests {

  struct Row: Decodable {
    let input: String
    let expected: String
    let category: String
    let slice: String
  }

  /// `<repo>/Tests/EnviousWisprTests/Resources/InverseTextNormalizer/`.
  static let resourceDir: URL = URL(filePath: #filePath)
    .deletingLastPathComponent()  // PostProcessing
    .deletingLastPathComponent()  // EnviousWisprTests
    .deletingLastPathComponent()  // Tests
    .deletingLastPathComponent()  // repo root
    .appending(path: "Tests/EnviousWisprTests/Resources/InverseTextNormalizer")

  static func loadRows(_ file: String = "parity.jsonl") throws -> [Row] {
    let text = try String(contentsOf: resourceDir.appending(path: file), encoding: .utf8)
    let decoder = JSONDecoder()
    return try text.split(separator: "\n").compactMap { line in
      let trimmed = line.trimmingCharacters(in: .whitespaces)
      guard trimmed.isEmpty == false else { return nil }
      return try decoder.decode(Row.self, from: Data(trimmed.utf8))
    }
  }

  /// Byte-for-byte compare the Swift engine against the oracle outputs in `rows`.
  /// Records a per-category breakdown + sample on failure; returns the mismatch count.
  static func checkParity(_ rows: [Row], label: String) -> Int {
    let itn = InverseTextNormalizer()
    var mismatches: [(Row, String)] = []
    var perCategoryTotal: [String: Int] = [:]
    var perCategoryFail: [String: Int] = [:]
    for row in rows {
      perCategoryTotal[row.category, default: 0] += 1
      let got = itn.normalize(row.input)
      if got != row.expected {
        perCategoryFail[row.category, default: 0] += 1
        if mismatches.count < 40 { mismatches.append((row, got)) }
      }
    }
    let failCount = perCategoryFail.values.reduce(0, +)
    if failCount > 0 {
      let sample = mismatches.map { item -> String in
        let (r, got) = item
        return "  [\(r.category)/\(r.slice)] in=\(r.input.debugDescription) "
          + "want=\(r.expected.debugDescription) got=\(got.debugDescription)"
      }.joined(separator: "\n")
      let byCat = perCategoryFail.sorted { $0.key < $1.key }
        .map { "\($0.key): \($0.value)/\(perCategoryTotal[$0.key] ?? 0)" }
        .joined(separator: ", ")
      let msg =
        "ITN parity [\(label)]: \(failCount)/\(rows.count) mismatches vs Python oracle.\n"
        + "By category (fail/total): \(byCat)\nFirst \(mismatches.count):\n\(sample)"
      Issue.record("\(msg)")
    }
    return failCount
  }

  /// Two degenerate oracle inputs are non-idempotent in the Python reference too (a 17-word
  /// "quadrillion" mega-number and a malformed "point five o six dollars" with no leading
  /// whole). Excluded from the idempotence property, NOT from parity — Swift still matches
  /// the oracle's first-pass output for both.
  static let knownNonIdempotentInputs: Set<String> = [
    "ninety seven quadrillion eight hundred eight trillion two hundred sixty four billion "
      + "seven hundred seventy two million seven hundred ninety two thousand five",
    "point five o six dollars",
  ]

  // MARK: - Primary: byte-for-byte parity with the Python oracle

  @Test("Swift ITN matches the Python oracle byte-for-byte across the curated corpus")
  func byteForByteParity() throws {
    let rows = try Self.loadRows()
    #expect(rows.count > 1500, "parity fixture looks truncated: \(rows.count) rows")
    #expect(Self.checkParity(rows, label: "curated") == 0)
  }

  /// Independent-data faithfulness: rows NOT baked into the curated fixture (the synthetic
  /// holdout + the public Google-TN set + real dictations, deduped against `parity.jsonl`).
  /// Passing here means the port is faithful to the oracle on UNSEEN inputs, not just the
  /// cases captured at build time.
  @Test("Swift ITN matches the oracle on the independent holdout (unseen inputs)")
  func holdoutParity() throws {
    let rows = try Self.loadRows("parity_holdout.jsonl")
    #expect(rows.count > 3000, "holdout fixture looks truncated: \(rows.count) rows")
    #expect(Self.checkParity(rows, label: "holdout") == 0)
  }

  // MARK: - Safety property: no corruption of natural prose (heaviest-weighted rubric)

  @Test("Natural-speech negatives pass through unchanged (no-corruption floor)")
  func negativesArePreserved() throws {
    let rows = try Self.loadRows().filter { $0.slice == "negative" }
    #expect(rows.isEmpty == false)
    let itn = InverseTextNormalizer()
    var corrupted: [(String, String)] = []
    for row in rows where itn.normalize(row.input) != row.expected {
      corrupted.append((row.input, itn.normalize(row.input)))
    }
    // Parity already pins these to the oracle; this is a focused readout of the safety floor.
    #expect(corrupted.isEmpty, "negatives diverged from oracle: \(corrupted.prefix(10))")
  }

  // MARK: - Safety property: idempotence (normalize is a fixed point of itself)

  @Test("Idempotence: normalizing an already-normalized output is a no-op")
  func idempotence() throws {
    let rows = try Self.loadRows()
    let itn = InverseTextNormalizer()
    var unstable: [(String, String, String)] = []
    for row in rows where Self.knownNonIdempotentInputs.contains(row.input) == false {
      let once = itn.normalize(row.input)
      let twice = itn.normalize(once)
      if twice != once {
        unstable.append((row.input, once, twice))
      }
    }
    #expect(
      unstable.isEmpty,
      "non-idempotent (beyond the 2 known degenerate inputs): \(unstable.prefix(10))")
  }

  // MARK: - Targeted: the specific fixes fresh-data validation surfaced

  // Expected values below are the verbatim Python-oracle outputs (verified at port time),
  // NOT hand-guessed — each demonstrates one fix the fresh-data validation surfaced.
  @Test(
    "Category fixes hold (oracle-verified)",
    arguments: [
      // o→0 in spoken digit reads, 10-digit phone — fix #5
      ("my number is o five five five one two three four five six", "my number is 055-512-3456"),
      // year-pair standalone — fix #6 / founder option 1
      ("i was born in nineteen eighty seven", "i was born in 1987"),
      // keep-magnitude house style — fix #7
      ("we raised eighty million dollars last year", "we raised $80 million last year"),
      // word-driven digit read with a zero-word, length ≤ 6
      ("the code is two zero three", "the code is 203"),
      // mixed-state phone (already-digit group + digit-words) — fix #4
      ("call me at 203 nine five four eight eight seven nine", "call me at 203-954-8879"),
      // strict-cardinal corruption guard: a non-cardinal run is left untouched (context for
      // "one twenty" belongs to the AI-polish layer, not the deterministic floor)
      ("there were one twenty people there", "there were one twenty people there"),
      // #145 follow-up: capitalized number words in an UNIT-ANCHORED numeric context
      // (currency / percent / decimal point) now format — they did not before because the
      // lexicon lookups were case-sensitive.
      ("Twenty dollars please", "$20 please"),
      ("Twenty percent off", "20% off"),
      // crash guard: a title-cased decimal must format, not trap on the force-unwrapped fraction
      // word ('Five'); the case-insensitive regex captures it, so the digit map must lowercase.
      ("Three Point Five", "3.5"),
      // adversarial negatives: a capitalized number word with NO unit anchor must stay a word,
      // never corrupt into a digit — covers prose ("One thing", "Two of us") AND proper nouns
      // that contain a scale word ("Hundred Acre Wood", "One Million Moms"). A bare/scale-only
      // capital is ambiguous between count and name, so the deterministic floor leaves it.
      ("One thing that I want to figure out", "One thing that I want to figure out"),
      ("Two of us went to the store", "Two of us went to the store"),
      ("Hundred Acre Wood", "Hundred Acre Wood"),
      ("One Million Moms", "One Million Moms"),
    ])
  func categoryFixes(input: String, expected: String) {
    #expect(InverseTextNormalizer().normalize(input) == expected)
  }
}
