// Generated by python3 artifacts/issue-996-edit-judge/hint-validation/generate_common_spot_words.py
// wordfreq==3.1.1, language=en, wordlist=best, Zipf >= 5.6.
// 224 lowercase English word tokens; regenerate with the command above.
// Apostrophes use spots.py's [a-z0-9']+ tokenization.
enum CommonEnglishSpotWords {
  static let words: Set<String> = [
    "a", "about", "after", "again", "against", "all", "also", "always",
    "am", "an", "and", "another", "any", "are", "around", "as",
    "at", "away", "back", "be", "because", "been", "before", "being",
    "best", "better", "between", "big", "both", "but", "by", "can",
    "can't", "city", "come", "company", "could", "day", "days", "did",
    "didn't", "do", "does", "doing", "don't", "down", "during", "each",
    "end", "even", "ever", "every", "family", "feel", "few", "find",
    "first", "for", "found", "free", "from", "game", "get", "give",
    "go", "going", "good", "got", "great", "had", "has", "have",
    "he", "he's", "help", "her", "here", "high", "him", "his",
    "home", "house", "how", "i", "i'm", "i've", "if", "in",
    "into", "is", "it", "it's", "its", "just", "keep", "know",
    "last", "left", "let", "life", "like", "little", "long", "look",
    "lot", "love", "made", "make", "man", "many", "may", "me",
    "might", "money", "more", "most", "mr", "much", "must", "my",
    "name", "need", "never", "new", "next", "night", "no", "not",
    "now", "number", "of", "off", "old", "on", "one", "only",
    "or", "other", "our", "out", "over", "own", "part", "people",
    "place", "play", "please", "put", "real", "really", "right", "s",
    "said", "same", "say", "school", "second", "see", "she", "should",
    "show", "since", "so", "some", "someone", "something", "state", "still",
    "such", "sure", "take", "team", "than", "that", "that's", "the",
    "their", "them", "then", "there", "these", "they", "thing", "things",
    "think", "this", "those", "three", "through", "time", "to", "too",
    "two", "under", "until", "up", "us", "use", "used", "very",
    "want", "was", "way", "we", "well", "were", "what", "when",
    "where", "which", "while", "who", "why", "will", "with", "without",
    "work", "world", "would", "year", "years", "you", "you're", "your",
  ]
}
