import EnviousWisprCore

/// One language's vetted deterministic-cleanup rule set (#1677).
///
/// Chunk 2 of the routing foundation carries only the identity: the canonical base code the route
/// selects on. The data a rule set will hold (number words, scale words, idiom rows, refusal tables,
/// generated by the offline generator and shipped as static Swift tables) arrives with the generator
/// PR, never as speculative schema here.
///
/// **Immutable by construction.** A value is created once, validated, and snapshotted into the work
/// closure before the actor hop, so no execution path rereads a registry by language code.
///
/// **The key is `LanguageNormalizer.baseCode`, not a second parser.** `nb`, `nn` collapse to `no`,
/// `cmn`/`yue`/`zh-Hans` to `zh`, `de-DE`/`DE` to `de`. English is never a rule set: the English
/// engine owns English, and the route reaches a language set only for an explicit NON-English value.
package struct LanguageRuleSet: Sendable, Equatable, Hashable {
  /// Canonical base code (`LanguageNormalizer.baseCode`), never `en`.
  package let baseCode: String

  /// Fails closed: a value `baseCode` rejects (`und`, `e`, `english`, whitespace) or one that
  /// canonicalises to English is not a language this layer may own.
  package init?(language raw: String) {
    guard let code = LanguageNormalizer.baseCode(raw), code != "en" else { return nil }
    self.baseCode = code
  }
}
