// GENERATED by website/scripts/generate-help-article-catalog.mjs. Do not edit by hand.
// Regenerate after any help-article add, removal or retitle, then redeploy (#3275).
export default {
  "catalogVersion": "e6fa1311e41a",
  "articles": [
    {
      "slug": "accessibility-permission-not-working",
      "title": "Accessibility Permission Not Working",
      "description": "Fixing the permission EnviousWispr needs to type into your apps."
    },
    {
      "slug": "adding-a-word-from-your-selection",
      "title": "Adding a Word From Your Selection",
      "description": "Highlight a word anywhere on your Mac, press the shortcut, and teach EnviousWispr the spelling."
    },
    {
      "slug": "adding-custom-words",
      "title": "Adding Custom Words",
      "description": "Teaching EnviousWispr names and words it keeps getting wrong."
    },
    {
      "slug": "ai-polish-and-cloud-data",
      "title": "AI Polish and Cloud Data",
      "description": "Which AI Polish options keep your text on your Mac, and what is sent when one does not."
    },
    {
      "slug": "api-key-security",
      "title": "API Key Security",
      "description": "Where your API key is stored and how to remove it."
    },
    {
      "slug": "app-crashes-or-asr-engine-crashes",
      "title": "When the App or Speech Engine Stops",
      "description": "What happens if the app or the speech engine stops, and what is saved."
    },
    {
      "slug": "apple-intelligence-not-available",
      "title": "Apple Intelligence Not Available",
      "description": "Why Apple Intelligence polish may be unavailable on your Mac."
    },
    {
      "slug": "apple-intelligence-setup",
      "title": "Apple Intelligence Setup",
      "description": "Setting up free, on-device AI Polish with Apple Intelligence."
    },
    {
      "slug": "auto-updates",
      "title": "Auto-Updates",
      "description": "How EnviousWispr updates itself."
    },
    {
      "slug": "bluetooth-and-airpods",
      "title": "Bluetooth and AirPods",
      "description": "Using AirPods or a Bluetooth headset, and what to expect from the sound."
    },
    {
      "slug": "canceling-a-recording",
      "title": "Canceling a Recording",
      "description": "Stop a recording, and choose whether to keep what you said."
    },
    {
      "slug": "choosing-a-speech-engine-parakeet-vs-whisperkit",
      "title": "Choosing a Speech Engine: Parakeet vs WhisperKit",
      "description": "Which of the two speech engines to use, and when to switch."
    },
    {
      "slug": "choosing-an-ai-provider-none-apple-intelligence-ollama-openai-gemini",
      "title": "Choosing an AI Provider",
      "description": "The AI Polish options, what each one costs, and which ones keep your text on your Mac."
    },
    {
      "slug": "choosing-your-microphone",
      "title": "Choosing Your Microphone",
      "description": "Letting EnviousWispr follow your Mac, or choosing a microphone yourself."
    },
    {
      "slug": "clipboard-preservation",
      "title": "Clipboard Preservation",
      "description": "How EnviousWispr avoids trampling what you already had copied."
    },
    {
      "slug": "customizing-your-keybind",
      "title": "Customizing Your Keybind",
      "description": "Set the keys that start, stop, and cancel dictation."
    },
    {
      "slug": "download-and-install",
      "title": "Download and Install",
      "description": "How to get EnviousWispr onto your Mac and open it the first time."
    },
    {
      "slug": "empty-or-missing-transcription",
      "title": "Empty or Missing Transcription",
      "description": "What to check when your microphone is not working and no text appears."
    },
    {
      "slug": "escape-recovery",
      "title": "Escape Recovery",
      "description": "Keep a recording you cancelled by mistake instead of losing it."
    },
    {
      "slug": "filler-word-removal",
      "title": "Filler Word Removal",
      "description": "Cutting um, uh and hmm out of your dictation."
    },
    {
      "slug": "first-word-gets-cut-off",
      "title": "First Word Gets Cut Off",
      "description": "Why the start of a dictation can go missing, and how to stop it."
    },
    {
      "slug": "granting-permissions-microphone-accessibility-and-automation",
      "title": "Granting Permissions (Microphone, Accessibility, and Automation)",
      "description": "The macOS permissions EnviousWispr asks for, and what each one is used for."
    },
    {
      "slug": "hallucination-protection",
      "title": "Hallucination Protection",
      "description": "The checks that catch AI output which does not match what you said."
    },
    {
      "slug": "hands-free-mode-long-dictation",
      "title": "Hands-Free Mode (Long Dictation)",
      "description": "For when you do not want to hold the key down: lock recording on and keep talking."
    },
    {
      "slug": "how-custom-word-correction-works",
      "title": "How Custom Word Correction Works",
      "description": "How EnviousWispr recognises the wrong versions of a word you added."
    },
    {
      "slug": "how-smart-polish-works-context-aware",
      "title": "How Smart Polish Works (Context-Aware)",
      "description": "The context EnviousWispr gives the AI so it corrects you better."
    },
    {
      "slug": "how-text-gets-pasted-into-your-app",
      "title": "How Text Gets Pasted Into Your App",
      "description": "How your dictation reaches the app you were typing in, and which apps work."
    },
    {
      "slug": "importing-and-exporting-custom-words",
      "title": "Importing and Exporting Custom Words",
      "description": "Moving your custom words between Macs, or bringing them in from another app."
    },
    {
      "slug": "is-enviouswispr-free",
      "title": "Is EnviousWispr Free?",
      "description": "Yes. What is included, and the one thing that can cost money."
    },
    {
      "slug": "live-preview-words-on-screen",
      "title": "Live Preview",
      "description": "Seeing your words on screen while you are still speaking."
    },
    {
      "slug": "live-transcription-streaming-asr",
      "title": "Faster Transcription",
      "description": "Whether to have text written while you are still speaking."
    },
    {
      "slug": "model-downloads-and-management",
      "title": "Model Downloads and Management",
      "description": "How the speech models are downloaded, and how to free the memory and disk they use."
    },
    {
      "slug": "multi-language-dictation",
      "title": "Multi-Language Dictation",
      "description": "Dictating in languages other than English."
    },
    {
      "slug": "noise-suppression",
      "title": "Noise Suppression",
      "description": "There is no noise suppression setting, and what to do about a noisy room."
    },
    {
      "slug": "numbers-dates-and-times",
      "title": "Numbers, Dates and Times",
      "description": "How spoken numbers, money, dates and phone numbers get written out."
    },
    {
      "slug": "ollama-polish-not-working",
      "title": "Ollama Polish Not Working",
      "description": "Fixing AI Polish when you are using Ollama."
    },
    {
      "slug": "paste-not-working",
      "title": "Paste Not Working?",
      "description": "What to check when your dictation does not appear in your app."
    },
    {
      "slug": "privacy-overview",
      "title": "Privacy Overview",
      "description": "What stays on your Mac, and when the app uses the network."
    },
    {
      "slug": "push-to-talk-mode",
      "title": "Push-to-Talk Mode",
      "description": "Hold the key, talk, let go. The default way to dictate."
    },
    {
      "slug": "recording-won-t-stop-or-seems-stuck",
      "title": "Recording Won't Stop or Seems Stuck",
      "description": "What to do when a recording seems to hang."
    },
    {
      "slug": "s1-mini-by-superwhisper-and-writing-style",
      "title": "S1-mini by Superwhisper and Its Writing Style Settings",
      "description": "The lightest on-device polish option, where it comes from, and what the Tone, Structure and Context pickers do."
    },
    {
      "slug": "self-learning-dictionary",
      "title": "Self-Learning Dictionary",
      "description": "When you fix a misheard word in text EnviousWispr pasted a moment ago, the right spelling joins your dictionary on its own, with three seconds to undo, and a word check on your Mac uses it in later dictations. Which apps it works in, how it decides, and what stays on your Mac."
    },
    {
      "slug": "sending-feedback",
      "title": "Sending Feedback From the App",
      "description": "Tell us about a bug or an idea without leaving EnviousWispr: the bug button beside Record opens a short form, your draft is saved as you type, and an email is optional."
    },
    {
      "slug": "sounds-and-appearance",
      "title": "Sounds and Appearance",
      "description": "Light and dark mode, where the recording bar sits and how it looks, the Dock icon, the app's language (English or Deutsch), recording sounds, and what happens to music while you dictate."
    },
    {
      "slug": "source-code-and-contributing",
      "title": "Source Code and Contributing",
      "description": "Where the code lives, what the license allows, and how to help."
    },
    {
      "slug": "spoken-punctuation-and-emoji",
      "title": "Spoken Punctuation and Emoji",
      "description": "How to dictate slash commands, punctuation marks and emoji, and which settings control them."
    },
    {
      "slug": "system-requirements",
      "title": "System Requirements",
      "description": "What you need to run EnviousWispr."
    },
    {
      "slug": "toggle-mode",
      "title": "Toggle Mode",
      "description": "Press once to start recording, press again to stop."
    },
    {
      "slug": "transcribe-a-file-speaker-labels",
      "title": "Speaker labels in Transcribe a File",
      "description": "How Transcribe a File tells speakers apart, how to rename them, and what Both and Not fully polished mean."
    },
    {
      "slug": "transcribe-a-file",
      "title": "Transcribe a File",
      "description": "Turn a voice memo, lecture, meeting or video you already have into clean text, on your Mac."
    },
    {
      "slug": "transcript-history",
      "title": "History",
      "description": "Finding, reusing, and deleting your past dictations and transcripts."
    },
    {
      "slug": "uninstalling-enviouswispr",
      "title": "Uninstalling EnviousWispr",
      "description": "Removing EnviousWispr, and the files it leaves behind."
    },
    {
      "slug": "updates-not-arriving-move-to-applications",
      "title": "Updates Never Arrive: Move EnviousWispr to Applications",
      "description": "If EnviousWispr is running from Downloads it cannot update itself. Here is how to fix it in about thirty seconds."
    },
    {
      "slug": "using-a-mouse-button-for-dictation",
      "title": "Using a Mouse Button for Dictation",
      "description": "Start dictation from a side button on a gaming mouse."
    },
    {
      "slug": "using-ollama-for-fully-offline-ai-polish",
      "title": "Using Ollama for Fully Offline AI Polish",
      "description": "Running AI Polish through a local model with Ollama."
    },
    {
      "slug": "using-snippets",
      "title": "Using Snippets",
      "description": "Say a short keyword and a trigger, and EnviousWispr pastes the text you saved."
    },
    {
      "slug": "voice-activity-detection-and-auto-stop",
      "title": "Voice Activity Detection and Auto-Stop",
      "description": "Having a recording end by itself once you stop talking."
    },
    {
      "slug": "what-data-is-collected",
      "title": "What Data Is Collected",
      "description": "What stays on your Mac, what the app never sends, and what it does collect."
    },
    {
      "slug": "what-is-ai-polish",
      "title": "What Is AI Polish?",
      "description": "What AI Polish changes about your dictation, and what it is designed not to do."
    },
    {
      "slug": "what-is-enviouswispr",
      "title": "What Is EnviousWispr?",
      "description": "EnviousWispr is a free, open-source dictation app for macOS. Hold a keybind, speak, and your words appear as text in whatever app you are using."
    },
    {
      "slug": "why-is-my-dictation-inaccurate",
      "title": "Why Is My Dictation Inaccurate?",
      "description": "The checks worth running when your dictation comes out wrong."
    },
    {
      "slug": "your-first-dictation",
      "title": "Your First Dictation",
      "description": "Record your first dictation and know what to expect."
    }
  ]
};
