import CryptoKit
import FluidAudio
import Foundation

/// Spells a word or phrase into Parakeet v3 token ids for decoder phrase boosting (#3338 C.3,
/// design #2610 §3.2). It returns the exact ids NVIDIA's tokenizer gives, or a refusal; it never
/// approximates, substitutes `<unk>`, drops a piece or returns a partial spelling.
///
/// The BPE work belongs to FluidAudio's `BpeTokenizer` (`encodeExact`, NFC with case kept). This
/// type adds the input contract NVIDIA's normalizer would otherwise decide: characters that
/// NFKC would change (full-width forms, ligatures, circled or superscript characters), controls,
/// format characters and any whitespace other than single spaces between words are refused,
/// because the speller does not run the tokenizer's precompiled character map.
///
/// The resource is `Resources/ParakeetSpeller/parakeet-v3-speller.json`, generated by
/// `scripts/parakeet-speller-data.py resource` (provenance inside the file and in `PROVENANCE.md`).
/// It is checked against `resourceSHA256` before use. No tokenizer is downloaded at runtime.
package struct ParakeetPhraseSpeller: Sendable {

  /// SHA-256 of the generated resource this build expects.
  package static let resourceSHA256 =
    "ebe7f485eb5e187449df47fb35ab47d4cf7e2810bd5b6efbd6bb968a872d6973"

  package enum LoadError: Error, Equatable {
    case resourceMissing(URL)
    case digestMismatch(actual: String)
    case malformed(String)
  }

  package enum Refusal: Error, Equatable, Sendable {
    /// Empty text, or a leading, trailing or repeated space.
    case emptyWord
    /// A control, format or non-space whitespace character.
    case unsupportedCharacter(Unicode.Scalar)
    /// NFKC would change the text; the speller does not apply compatibility mappings.
    case compatibilityCharacters
    /// A piece is not in the Parakeet v3 vocabulary (for example Greek final sigma or "&").
    case unknownPiece(String)
    /// A piece resolves only to a special token.
    case specialTokenPiece(String)
  }

  private let tokenizer: BpeTokenizer

  /// Loads and digest-checks the speller resource at `resource`.
  package static func load(resource: URL) throws -> ParakeetPhraseSpeller {
    guard FileManager.default.fileExists(atPath: resource.path) else {
      throw LoadError.resourceMissing(resource)
    }
    let data = try Data(contentsOf: resource)
    let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    guard digest == resourceSHA256 else { throw LoadError.digestMismatch(actual: digest) }
    do {
      return ParakeetPhraseSpeller(tokenizer: try BpeTokenizer.load(tokenizerFile: resource))
    } catch {
      throw LoadError.malformed(String(describing: error))
    }
  }

  private init(tokenizer: BpeTokenizer) {
    self.tokenizer = tokenizer
  }

  /// The exact Parakeet v3 token ids for `text`, or why it cannot be spelled.
  package func spell(_ text: String) -> Result<[Int], Refusal> {
    let canonical = text.precomposedStringWithCanonicalMapping
    for scalar in canonical.unicodeScalars where scalar != " " {
      // The tokenizer's own word-boundary mark: the Metaspace pre-tokenizer splits on it and
      // does not double it (official tokenizer: "▁" -> no ids), which encodeExact does not model.
      if scalar == "\u{2581}" {
        return .failure(.unsupportedCharacter(scalar))
      }
      switch scalar.properties.generalCategory {
      case .control, .format, .spaceSeparator, .lineSeparator, .paragraphSeparator,
        .surrogate, .privateUse, .unassigned:
        return .failure(.unsupportedCharacter(scalar))
      default:
        continue
      }
    }
    // Compare scalars, not `String ==` (which treats canonically equivalent strings as equal).
    guard
      Array(canonical.precomposedStringWithCompatibilityMapping.unicodeScalars)
        == Array(canonical.unicodeScalars)
    else { return .failure(.compatibilityCharacters) }

    switch tokenizer.encodeExact(canonical, normalization: .canonicalCasePreserving) {
    case .success(let ids): return .success(ids)
    case .failure(.emptyWord): return .failure(.emptyWord)
    case .failure(.boundaryMarkInInput): return .failure(.unsupportedCharacter("\u{2581}"))
    case .failure(.unknownPiece(let piece)): return .failure(.unknownPiece(piece))
    case .failure(.specialTokenPiece(let piece)): return .failure(.specialTokenPiece(piece))
    }
  }
}
